version: '3'
services:
  ui:
    image: 'keziban/todoreact:latest'
    container_name: brc-frontend
    depends_on:
      - app
      - db
      
    ports:
      - "80:3000"
    environment: 
      - REACT_APP_BASE_URL=http://localhost:9090/
    networks:
      - carrental-net
  app:
    image: 'keziban/todobac:latest'
    container_name: brc-backend
    depends_on:
      - db
     
    ports:
      - "9090:9090"
    restart: always
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/ juniortodoo
    networks:
      - carrental-net
          
  db:
    image: 'keziban/todopostgre:latest'
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pp123456789
      - POSTGRES_DB=juniortodo

    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - carrental-net

volumes:
    db-data:
networks:
    carrental-net:
        driver: bridge
